# Trabajo Practico n4 - Introduccion a numpy.
## Criterios de evaluación.

* Se deben utilizar nombres de variables descriptivos y claros (Utilizar la nomeclatura correspondiente para los nombres de variables).
* Comentarios claros y concisos que expliquen el propósito de cada sección del código.
* Utilizar mensajes de commit **descriptivos**. (Puedes utilizar la extension CONVENTIONAL COMMIT de VS-CODE). 
* Entrega en tiempo y forma.
* Todo el código desarrollado debe ser subido a un repositorio en GitHub (el nombre del repositorio de seguir la siguiente estructura: tp4_tlp3_nombre_apellido).
* Para resolver las actividades se debe insertar casillas de codigo entre cada actividad del cuaderno de Jupyter

### ¡Importante!
**El incumplimiento de los criterios de evaluación restará puntos en la nota final del práctico!**

**Importaciones:**

In [1]:
import numpy as np
from random import randint

**Actividad 1:**: Crea un array de NumPy que contenga los números del 0 al 9. (Debes utilizar un metodo de numpy para su creacion.)

In [2]:
# array utilizando la funcion "arange" en numpy

array = np.arange(10)
print(array)

[0 1 2 3 4 5 6 7 8 9]


**Actividad 2:** Crea un array de 5 ceros, y luego cambia el tercer elemento (índice 2) para que sea 5. (Debes utilizar un metodo de numpy para su creacion.)

In [3]:
# array de 5 ceros utilizando la función "zeros" en numpy

array2 = np.zeros(5,int)
print(array2)

# se cambia el elemento de incide 2 para que sea 5

array2[2] = 5
print(array2)

[0 0 0 0 0]
[0 0 5 0 0]


**Actividad 3:** Genera una matriz 3x3 de números aleatorios entre 0 y 1.

In [4]:
# matriz de 3x3 utilizando la función "random.rand" en numpy
matriz = np.random.rand(3,3)
print(matriz)

[[0.31332497 0.6652684  0.2619886 ]
 [0.45766937 0.66832104 0.23135351]
 [0.31563614 0.17419294 0.1381817 ]]


**Actividad 4:** Dado el siguiente array `arr = np.array([10, 20, 30, 40, 50])`
1. Suma 5 a cada elemento.
2. Multiplica todo por un numero aleatorio (utiliza el modulo random para generarlo.)

In [11]:
# dado el array proporcionado se procede a sumar 5 a cada elemento
arr = np.array([10, 20, 30, 40, 50])
print(arr)

arr2 = arr + 5
print(arr2)

# ahora se multipica todo por un numero aleatorio utilizando random.randint

num = np.random.randint(1,20)

arr3 = arr2 * num
print(arr3)


[10 20 30 40 50]
[15 25 35 45 55]
[ 30  50  70  90 110]


**Actividad 5:** Crea una matriz identidad de tamaño 4x4 (unos en la diagonal principal y ceros en el resto).

In [12]:
# se crea la matriz de indentidad de 4x4 utilizando la funcion "eye" de numpy
matriz2 = np.eye(4)
print(matriz2)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


**Actividad 6:** Crea un array que comience en 0 hasta el 20, pero que solo tenga numeros pares yu luego realiza las 4 operaciones basicas. (suma, resta, multiplicacion, division).

In [14]:
# se crea un array de numeros pares hasta el 20 

array3 = np.arange(0,21,2)
print(array3)

#suma 
suma = array3 + 2
print(suma)

# resta
resta = array3 - 2
print(resta)

# multiplicacion = array3 * 2
multiplicacion = array3 * 2
print(multiplicacion)

# division = array3 / 2 , se utiliza el metodo astype para convertir el resultado a numero entero
division = (array3 / 2).astype(int)
print(division)


[ 0  2  4  6  8 10 12 14 16 18 20]
[ 2  4  6  8 10 12 14 16 18 20 22]
[-2  0  2  4  6  8 10 12 14 16 18]
[ 0  4  8 12 16 20 24 28 32 36 40]
[ 0  1  2  3  4  5  6  7  8  9 10]
